/*
 * 中华乐事 · Java 侧菜品注册表生成器
 * 用法：node tools/cooking/javagen.js
 *
 * 用 data.js 里的 DISH_ITEMS（含 nutrition / saturation / effect）重写
 * src/main/java/com/qiyi/chinesedelight/item/ModDishItems.java。
 *
 * 这样「加菜」只需要改 data.js，然后跑：
 *     node tools/cooking/generate.js && node tools/cooking/javagen.js && node tools/cooking/validate.js
 * 不要手改 ModDishItems.java，会被覆盖。
 */
const fs = require('fs');
const path = require('path');
const data = require('./data');

const ROOT = path.resolve(__dirname, '..', '..');
const OUT = path.join(ROOT, 'src', 'main', 'java', 'com', 'qiyi', 'chinesedelight', 'item', 'ModDishItems.java');

/** 效果名 → Java 表达式 */
const EFFECTS = {
    speed: ['MobEffects.MOVEMENT_SPEED', 300],
    haste: ['MobEffects.DIG_SPEED', 300],
    regen: ['MobEffects.REGENERATION', 120],
    strength: ['MobEffects.DAMAGE_BOOST', 300],
    resist: ['MobEffects.DAMAGE_RESISTANCE', 300],
    night_vision: ['MobEffects.NIGHT_VISION', 600],
};

function effectExpr(spec) {
    if (!spec || spec === 'none') return 'List.of()';
    if (spec === 'penalty') return 'penalty()';
    const [effect, ticks] = EFFECTS[spec] || [];
    if (!effect) throw new Error(`未知效果: ${spec}`);
    return `List.of(new MobEffectInstance(${effect}, ${ticks}, 0))`;
}

const lines = [];
lines.push('package com.qiyi.chinesedelight.item;');
lines.push('');
lines.push('import net.minecraft.world.effect.MobEffectInstance;');
lines.push('import net.minecraft.world.effect.MobEffects;');
lines.push('import net.minecraft.world.food.FoodProperties;');
lines.push('import net.minecraft.world.item.Item;');
lines.push('import net.neoforged.neoforge.registries.DeferredItem;');
lines.push('import net.neoforged.neoforge.registries.DeferredRegister;');
lines.push('');
lines.push('import java.util.ArrayList;');
lines.push('import java.util.LinkedHashMap;');
lines.push('import java.util.List;');
lines.push('import java.util.Map;');
lines.push('');
lines.push('/**');
lines.push(' * Dish food properties.');
lines.push(' *');
lines.push(' * <p><b>Generated by tools/cooking/javagen.js - do not edit by hand.</b>');
lines.push(' * To add or retune a dish, edit DISH_ITEMS in tools/cooking/data.js and regenerate.');
lines.push(' *');
lines.push(' * <p>Which dish a pot produces is decided by the datapack (chinesedelight:dish);');
lines.push(' * what eating it does is decided here. 1.21.1 expresses food effects through');
lines.push(' * FoodProperties.Builder#effect; the 1.21.5 Consumable component does not exist yet.');
lines.push(' */');
lines.push('public final class ModDishItems {');
lines.push('    public record DishFood(String id, int nutrition, float saturation, List<MobEffectInstance> effects) {');
lines.push('    }');
lines.push('');
lines.push('    /** Penalty dishes: poison + nausea. */');
lines.push('    private static List<MobEffectInstance> penalty() {');
lines.push('        return List.of(');
lines.push('                new MobEffectInstance(MobEffects.POISON, 100, 0),');
lines.push('                new MobEffectInstance(MobEffects.CONFUSION, 200, 0));');
lines.push('    }');
lines.push('');
lines.push('    /** Every dish this class registers, in creative-tab order. */');
lines.push('    public static final List<DishFood> ALL;');
lines.push('');
lines.push('    static {');
lines.push('        List<DishFood> dishes = new ArrayList<>();');

const skipped = [];
for (const item of data.DISH_ITEMS) {
    // existing: true 的物品已经在 ModItems 里注册，重复注册会导致启动失败
    if (item.existing) {
        skipped.push(item.id);
        continue;
    }
    const nutrition = item.nutrition ?? 6;
    const saturation = (item.saturation ?? 0.6).toFixed(1);
    lines.push(`        dishes.add(new DishFood("${item.id}", ${nutrition}, ${saturation}F, ${effectExpr(item.effect)}));`);
}

lines.push('        ALL = List.copyOf(dishes);');
lines.push('    }');
lines.push('');
if (skipped.length > 0) {
    lines.push('    // NOTE: ' + skipped.join(', ') + ' are already registered in ModItems,');
    lines.push('    // so they are deliberately not registered here.');
    lines.push('');
}
lines.push('');
lines.push('    private ModDishItems() {');
lines.push('    }');
lines.push('');
lines.push('    private static final Map<String, DeferredItem<Item>> REGISTERED = new LinkedHashMap<>();');
lines.push('');
lines.push('    /** Look up a dish item by id (the datapack result uses the same id). */');
lines.push('    public static DeferredItem<Item> get(String id) {');
lines.push('        DeferredItem<Item> item = REGISTERED.get(id);');
lines.push('        if (item == null) {');
lines.push('            throw new IllegalArgumentException("Unknown dish item: " + id);');
lines.push('        }');
lines.push('        return item;');
lines.push('    }');
lines.push('');
lines.push('    public static void register(DeferredRegister.Items items) {');
lines.push('        for (DishFood food : ALL) {');
lines.push('            FoodProperties.Builder builder = new FoodProperties.Builder()');
lines.push('                    .nutrition(food.nutrition())');
lines.push('                    .saturationModifier(food.saturation());');
lines.push('            for (MobEffectInstance effect : food.effects()) {');
lines.push('                builder.effect(() -> effect, 1.0F);');
lines.push('            }');
lines.push('            FoodProperties properties = builder.build();');
lines.push('            REGISTERED.put(food.id(), items.registerItem(food.id(), Item::new, new Item.Properties().food(properties)));');
lines.push('        }');
lines.push('    }');
lines.push('}');
lines.push('');

fs.writeFileSync(OUT, lines.join('\n'));
console.log(`写入 ModDishItems.java：注册 ${data.DISH_ITEMS.length - skipped.length} 道菜` +
    (skipped.length ? `，跳过已在 ModItems 注册的 ${skipped.length} 个（${skipped.join(', ')}）` : ''));
