package com.qiyi.chinesedelight.item;

import net.minecraft.world.effect.MobEffectInstance;
import net.minecraft.world.effect.MobEffects;
import net.minecraft.world.food.FoodProperties;
import net.minecraft.world.item.Item;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredRegister;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Dish food properties.
 *
 * <p><b>Generated by tools/cooking/javagen.js - do not edit by hand.</b>
 * To add or retune a dish, edit DISH_ITEMS in tools/cooking/data.js and regenerate.
 *
 * <p>Which dish a pot produces is decided by the datapack (chinesedelight:dish);
 * what eating it does is decided here. 1.21.1 expresses food effects through
 * FoodProperties.Builder#effect; the 1.21.5 Consumable component does not exist yet.
 */
public final class ModDishItems {
    public record DishFood(String id, int nutrition, float saturation, List<MobEffectInstance> effects) {
    }

    /** Penalty dishes: poison + nausea. */
    private static List<MobEffectInstance> penalty() {
        return List.of(
                new MobEffectInstance(MobEffects.POISON, 100, 0),
                new MobEffectInstance(MobEffects.CONFUSION, 200, 0));
    }

    /** Every dish this class registers, in creative-tab order. */
    public static final List<DishFood> ALL;

    static {
        List<DishFood> dishes = new ArrayList<>();
        dishes.add(new DishFood("scallion_egg", 7, 0.7F, List.of()));
        dishes.add(new DishFood("steamed_egg", 5, 0.7F, List.of(new MobEffectInstance(MobEffects.REGENERATION, 120, 0))));
        dishes.add(new DishFood("mapo_tofu", 8, 1.0F, List.of(new MobEffectInstance(MobEffects.MOVEMENT_SPEED, 300, 0))));
        dishes.add(new DishFood("spicy_tofu", 7, 0.8F, List.of(new MobEffectInstance(MobEffects.MOVEMENT_SPEED, 300, 0))));
        dishes.add(new DishFood("home_style_tofu", 7, 0.8F, List.of()));
        dishes.add(new DishFood("mushroom_tofu", 7, 0.8F, List.of()));
        dishes.add(new DishFood("cabbage_tofu_soup", 6, 0.7F, List.of(new MobEffectInstance(MobEffects.REGENERATION, 120, 0))));
        dishes.add(new DishFood("edamame_dish", 4, 0.5F, List.of()));
        dishes.add(new DishFood("dried_tofu_stirfry", 7, 0.8F, List.of(new MobEffectInstance(MobEffects.DAMAGE_BOOST, 300, 0))));
        dishes.add(new DishFood("garlic_vegetable", 6, 0.6F, List.of()));
        dishes.add(new DishFood("stir_fried_greens", 5, 0.5F, List.of()));
        dishes.add(new DishFood("cabbage_stirfry", 5, 0.5F, List.of()));
        dishes.add(new DishFood("potato_shreds", 6, 0.6F, List.of()));
        dishes.add(new DishFood("sour_potato_shreds", 7, 0.7F, List.of(new MobEffectInstance(MobEffects.DIG_SPEED, 300, 0))));
        dishes.add(new DishFood("vegetable_stew", 6, 0.6F, List.of()));
        dishes.add(new DishFood("mushroom_stirfry", 6, 0.6F, List.of()));
        dishes.add(new DishFood("spiced_mix", 4, 0.4F, List.of()));
        dishes.add(new DishFood("plain_mix", 4, 0.4F, List.of()));
        dishes.add(new DishFood("fish_fragrant_pork", 9, 1.1F, List.of(new MobEffectInstance(MobEffects.MOVEMENT_SPEED, 300, 0))));
        dishes.add(new DishFood("twice_cooked_pork", 9, 1.1F, List.of(new MobEffectInstance(MobEffects.DAMAGE_BOOST, 300, 0))));
        dishes.add(new DishFood("braised_pork", 10, 1.2F, List.of(new MobEffectInstance(MobEffects.DAMAGE_RESISTANCE, 300, 0))));
        dishes.add(new DishFood("beef_potato_stew", 10, 1.2F, List.of(new MobEffectInstance(MobEffects.DAMAGE_BOOST, 300, 0))));
        dishes.add(new DishFood("chili_pork", 8, 1.0F, List.of(new MobEffectInstance(MobEffects.MOVEMENT_SPEED, 300, 0))));
        dishes.add(new DishFood("scallion_beef", 9, 1.1F, List.of(new MobEffectInstance(MobEffects.DAMAGE_BOOST, 300, 0))));
        dishes.add(new DishFood("cumin_mutton", 9, 1.1F, List.of(new MobEffectInstance(MobEffects.DAMAGE_BOOST, 300, 0))));
        dishes.add(new DishFood("chicken_mushroom", 9, 1.1F, List.of(new MobEffectInstance(MobEffects.REGENERATION, 120, 0))));
        dishes.add(new DishFood("ginger_chicken", 8, 1.0F, List.of(new MobEffectInstance(MobEffects.REGENERATION, 120, 0))));
        dishes.add(new DishFood("meat_stirfry", 7, 0.8F, List.of()));
        dishes.add(new DishFood("steamed_fish", 8, 1.0F, List.of(new MobEffectInstance(MobEffects.NIGHT_VISION, 600, 0))));
        dishes.add(new DishFood("braised_fish", 8, 1.0F, List.of(new MobEffectInstance(MobEffects.NIGHT_VISION, 600, 0))));
        dishes.add(new DishFood("yangzhou_fried_rice", 10, 1.2F, List.of(new MobEffectInstance(MobEffects.DIG_SPEED, 300, 0))));
        dishes.add(new DishFood("egg_fried_rice", 9, 1.0F, List.of(new MobEffectInstance(MobEffects.DIG_SPEED, 300, 0))));
        dishes.add(new DishFood("beef_noodle_soup", 10, 1.2F, List.of(new MobEffectInstance(MobEffects.DAMAGE_BOOST, 300, 0))));
        dishes.add(new DishFood("scallion_oil_noodles", 8, 0.9F, List.of(new MobEffectInstance(MobEffects.DIG_SPEED, 300, 0))));
        dishes.add(new DishFood("fried_noodles", 8, 0.9F, List.of()));
        dishes.add(new DishFood("sour_noodles", 8, 0.9F, List.of(new MobEffectInstance(MobEffects.MOVEMENT_SPEED, 300, 0))));
        dishes.add(new DishFood("dumpling", 9, 1.1F, List.of(new MobEffectInstance(MobEffects.DAMAGE_RESISTANCE, 300, 0))));
        dishes.add(new DishFood("scallion_pancake", 7, 0.8F, List.of()));
        dishes.add(new DishFood("egg_drop_soup", 5, 0.7F, List.of(new MobEffectInstance(MobEffects.REGENERATION, 120, 0))));
        dishes.add(new DishFood("hot_sour_soup", 6, 0.8F, List.of(new MobEffectInstance(MobEffects.MOVEMENT_SPEED, 300, 0))));
        dishes.add(new DishFood("kelp_soup", 5, 0.7F, List.of(new MobEffectInstance(MobEffects.NIGHT_VISION, 600, 0))));
        dishes.add(new DishFood("mushroom_soup", 6, 0.8F, List.of(new MobEffectInstance(MobEffects.REGENERATION, 120, 0))));
        dishes.add(new DishFood("cold_kelp", 4, 0.5F, List.of()));
        dishes.add(new DishFood("mush_default", 2, 0.1F, penalty()));
        dishes.add(new DishFood("mush_meat", 2, 0.1F, penalty()));
        dishes.add(new DishFood("mush_fish", 2, 0.1F, penalty()));
        dishes.add(new DishFood("mush_veggie", 2, 0.1F, penalty()));
        ALL = List.copyOf(dishes);
    }

    // NOTE: omelet, riceporridge, steamedbun are already registered in ModItems,
    // so they are deliberately not registered here.


    private ModDishItems() {
    }

    private static final Map<String, DeferredItem<Item>> REGISTERED = new LinkedHashMap<>();

    /** Look up a dish item by id (the datapack result uses the same id). */
    public static DeferredItem<Item> get(String id) {
        DeferredItem<Item> item = REGISTERED.get(id);
        if (item == null) {
            throw new IllegalArgumentException("Unknown dish item: " + id);
        }
        return item;
    }

    public static void register(DeferredRegister.Items items) {
        for (DishFood food : ALL) {
            FoodProperties.Builder builder = new FoodProperties.Builder()
                    .nutrition(food.nutrition())
                    .saturationModifier(food.saturation());
            for (MobEffectInstance effect : food.effects()) {
                builder.effect(() -> effect, 1.0F);
            }
            FoodProperties properties = builder.build();
            REGISTERED.put(food.id(), items.registerItem(food.id(), Item::new, new Item.Properties().food(properties)));
        }
    }
}
